# Generated by Django 4.1.5 on 2023-01-21 15:41

import app.login.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True, verbose_name='Название направления')),
                ('key', models.CharField(max_length=255, null=True, verbose_name='Ключ направления')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, null=True, unique=True, verbose_name='Логин')),
                ('password', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Пароль')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('source_modified', models.DateField(default=datetime.date(1970, 1, 1), verbose_name='Дата изменения в источнике')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Персонал')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'managed': False,
            },
            managers=[
                ('objects', app.login.models.MyUserManager()),
            ],
        ),
    ]
