# Generated by Django 4.1.5 on 2023-01-27 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=12, unique=True, verbose_name='Артикул')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp', models.IntegerField(blank=True, choices=[(1, 'Wildberries'), (2, 'Ozon')], null=True, verbose_name='Маркетплейс')),
                ('competition', models.IntegerField(blank=True, choices=[(1, 'Прямой'), (2, 'Аналог')], null=True, verbose_name='Тип конкуренции')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='product_search.product', verbose_name='Артикул')),
            ],
        ),
    ]
