# Generated by Django 4.1.5 on 2023-01-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=12, unique=True, verbose_name='SKU'),
        ),
    ]
