# Generated by Django 4.1.5 on 2023-01-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True, verbose_name='Название сборки')),
                ('skus', models.ManyToManyField(blank=True, null=True, related_name='assembly_sku', to='product_search.product', verbose_name='Идентификаторы в сборке')),
            ],
        ),
    ]
