# Generated by Django 4.1.5 on 2023-01-31 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_search', '0003_assembly'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assembly_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
