# Generated by Django 4.1.5 on 2023-02-03 15:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0004_assembly_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Last30DaysData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='assembly',
            name='skus',
            field=models.ManyToManyField(blank=True, related_name='assembly_sku', to='product_search.product', verbose_name='Идентификаторы в сборке'),
        ),
        migrations.CreateModel(
            name='PeriodData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата начала периода')),
                ('date_end', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата окончания периода')),
                ('name_month', models.CharField(max_length=255, null=True, verbose_name='Название месяца')),
                ('lost_profit', models.FloatField(blank=True, null=True, verbose_name='Упущенная выручка')),
                ('revenue', models.FloatField(blank=True, null=True, verbose_name='Выручка за период')),
                ('final_price_average', models.FloatField(blank=True, null=True, verbose_name='Средняя цена за период (выручка / число продаж)')),
                ('sales', models.IntegerField(blank=True, null=True, verbose_name='Количество проданных единиц товара за период')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_sku', to='product_search.product', verbose_name='Артикул')),
            ],
        ),
    ]
