# Generated by Django 4.1.5 on 2023-02-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0005_last30daysdata_alter_assembly_skus_perioddata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perioddata',
            name='name_month',
        ),
    ]
