# Generated by Django 4.1.5 on 2023-02-05 12:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0007_alter_assembly_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='last30daysdata',
            name='categories',
            field=models.FloatField(blank=True, null=True, verbose_name='Средняя позиция в выдаче'),
        ),
        migrations.AddField(
            model_name='last30daysdata',
            name='comments',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество отзывов'),
        ),
        migrations.AddField(
            model_name='last30daysdata',
            name='date_update',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата загрузки'),
        ),
        migrations.AddField(
            model_name='last30daysdata',
            name='final_price_average',
            field=models.FloatField(blank=True, null=True, verbose_name='Средняя цена за период (выручка / число продаж) за последние 30 дней'),
        ),
        migrations.AddField(
            model_name='last30daysdata',
            name='first_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Первое появление'),
        ),
        migrations.AddField(
            model_name='last30daysdata',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг карточки'),
        ),
        migrations.AddField(
            model_name='last30daysdata',
            name='revenue',
            field=models.FloatField(blank=True, null=True, verbose_name='Выручка за последние 30 дней'),
        ),
        migrations.AddField(
            model_name='last30daysdata',
            name='sales',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество проданных единиц товара за период за последние 30 дней'),
        ),
        migrations.AddField(
            model_name='last30daysdata',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days_data', to='product_search.product', verbose_name='Артикул'),
        ),
    ]
