# Generated by Django 4.1.5 on 2023-02-05 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0008_last30daysdata_categories_last30daysdata_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Категория')),
            ],
        ),
        migrations.RenameField(
            model_name='last30daysdata',
            old_name='categories',
            new_name='categories_pos',
        ),
        migrations.AddField(
            model_name='last30daysdata',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days_data_category', to='product_search.categories', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='perioddata',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_sku_category', to='product_search.categories', verbose_name='Категория'),
        ),
    ]
