# Generated by Django 4.1.5 on 2023-02-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0010_last30daysdata_lost_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last30daysdata',
            name='first_date',
            field=models.DateField(blank=True, null=True, verbose_name='Первое появление'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='mp',
            field=models.IntegerField(blank=True, choices=[(1, 'WB'), (2, 'OZ')], null=True, verbose_name='Маркетплейс'),
        ),
    ]
