# Generated by Django 4.1.5 on 2023-02-08 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0011_alter_last30daysdata_first_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productproperty',
            name='assembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_assembly', to='product_search.product', verbose_name='Сборка'),
        ),
        migrations.AlterField(
            model_name='productproperty',
            name='competition',
            field=models.IntegerField(blank=True, choices=[(1, 'Прямой'), (2, 'Аналог'), (3, 'Анализируемый товар')], null=True, verbose_name='Тип конкуренции'),
        ),
    ]
