# Generated by Django 4.1.5 on 2023-02-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0012_productproperty_assembly_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productproperty',
            name='mp',
        ),
        migrations.AddField(
            model_name='product',
            name='mp',
            field=models.IntegerField(blank=True, choices=[(1, 'WB'), (2, 'OZ')], null=True, verbose_name='Маркетплейс'),
        ),
    ]
