# Generated by Django 4.1.5 on 2023-02-08 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0013_remove_productproperty_mp_product_mp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productproperty',
            name='assembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_assembly', to='product_search.assembly', verbose_name='Сборка'),
        ),
    ]
