# Generated by Django 4.1.5 on 2023-02-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0014_alter_productproperty_assembly'),
    ]

    operations = [
        migrations.AddField(
            model_name='last30daysdata',
            name='last_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Упущенная выручка'),
        ),
    ]
