# Generated by Django 4.1.5 on 2023-02-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0015_last30daysdata_last_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='last30daysdata',
            name='graph',
            field=models.JSONField(blank=True, null=True, verbose_name='График продаж'),
        ),
        migrations.AddField(
            model_name='last30daysdata',
            name='most_sales',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена 80% продаж'),
        ),
        migrations.AddField(
            model_name='last30daysdata',
            name='price_graph',
            field=models.JSONField(blank=True, null=True, verbose_name='График цены'),
        ),
        migrations.AlterField(
            model_name='last30daysdata',
            name='last_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Последняя цена'),
        ),
    ]
