# Generated by Django 4.1.5 on 2023-02-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0016_last30daysdata_graph_last30daysdata_most_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='last30daysdata',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Наименование позиции'),
        ),
    ]
