# Generated by Django 4.1.5 on 2023-02-21 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0017_last30daysdata_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='product_search.product', verbose_name='Фото sku')),
            ],
        ),
    ]
