# Generated by Django 4.1.5 on 2023-02-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0018_productphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productphoto',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на фото'),
        ),
    ]
