# Generated by Django 4.1.5 on 2023-02-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0020_productphoto_filename_alter_productphoto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Clothes'), (2, 'Other')], null=True, verbose_name='Тип (Одежда/Остальное)'),
        ),
    ]
