# Generated by Django 4.1.5 on 2023-02-22 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0021_assembly_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='last30daysdata',
            name='client_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Итоговая цена для посетителя, с учетом СПП'),
        ),
        migrations.AddField(
            model_name='last30daysdata',
            name='client_sale',
            field=models.FloatField(blank=True, null=True, verbose_name='Размер Скидки Постоянного Покупателя'),
        ),
        migrations.AddField(
            model_name='last30daysdata',
            name='days_in_stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дней в наличии'),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Одежда'), (2, 'Остальное')], null=True, verbose_name='Тип (Одежда/Остальное)'),
        ),
        migrations.CreateModel(
            name='SizeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.IntegerField(blank=True, null=True, verbose_name='Количество проданных единиц товара за период за последние 30 дней')),
                ('size_name', models.TextField(blank=True, null=True, verbose_name='Размер')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Название')),
                ('size_origin', models.TextField(blank=True, null=True, verbose_name='Размер поставщика')),
                ('balance', models.IntegerField(blank=True, null=True, verbose_name='Остаток')),
                ('sku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='product_search.product', verbose_name='Артикул')),
            ],
        ),
    ]
