# Generated by Django 4.1.5 on 2023-02-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0022_last30daysdata_client_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizeproduct',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='sizeproduct',
            name='sales',
        ),
    ]
