# Generated by Django 4.1.5 on 2023-02-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0024_sizeproduct_balance_sizeproduct_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='last30daysdata',
            name='link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на товар'),
        ),
    ]
