# Generated by Django 4.1.5 on 2023-02-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0025_last30daysdata_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='last30daysdata',
            name='brand',
            field=models.TextField(blank=True, null=True, verbose_name='Бренд'),
        ),
    ]
