# Generated by Django 4.1.5 on 2023-02-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_search', '0026_last30daysdata_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='last30daysdata',
            name='balance',
            field=models.JSONField(blank=True, null=True, verbose_name='Остатки'),
        ),
        migrations.AlterField(
            model_name='last30daysdata',
            name='categories_pos',
            field=models.FloatField(blank=True, default=0, verbose_name='Средняя позиция в выдаче'),
        ),
        migrations.AlterField(
            model_name='last30daysdata',
            name='client_sale',
            field=models.FloatField(blank=True, default=0, verbose_name='Размер Скидки Постоянного Покупателя'),
        ),
    ]
